### ISSUE TITLE
最新版本   get 的时候  refer  ContentType  都设置不了 

### ISSUE THREAD

**Issue by gitlsl** [iccfish/fslib.network#3]
最新版本   get 的时候  refer  ContentType  都设置不了

**Comment by iccfish** [comment]
- 测试代码Refer没问题
- ContentType因为没有发送数据所以本来就无法设置

建议提供测试代码。

**Comment by gitlsl** [comment]
@iccfish 
   var client  = new HttpClient();

   var ctx = client.Create<string>(HttpMethod.Get, "http://www.cnblogs.com/").Send();
  ctx = client.Create<string>(HttpMethod.Get, "http://www.baidu.com/",refer: "http://www.baidu.com/").Send();

另外 get 的时候 带上ContentType的网站很多啊

**Comment by iccfish** [comment]
测试代码并没有问题，Refer被正确发出。
![qq 20160914204125](https://cloud.githubusercontent.com/assets/1091653/18512431/ab835562-7abb-11e6-8408-4a01407408bb.jpg)

Get的时候需要ContentType的场合请给出具体例子。。

**Comment by gitlsl** [comment]
![qq 20160914204623](https://cloud.githubusercontent.com/assets/10542685/18512598/869f59ac-7abc-11e6-94f1-956c6c5c59eb.png)
![qq 20160914204716](https://cloud.githubusercontent.com/assets/10542685/18512610/8bc8107c-7abc-11e6-9cb1-cb5f232a2d53.png)
![qq 20160914204745](https://cloud.githubusercontent.com/assets/10542685/18512663/c5a15ce0-7abc-11e6-9286-cb2ed9fa3cbe.png)

refer的设置我这边确实是先 访问域名A  再访问域名B refer设B   但抓包 refer是 A
contenttype 网易都这样的。。。

`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="extension.fishlee.net" version="1.4.2.0" targetFramework="net45" />
  <package id="network.fishlee.net" version="2.2.1.0" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net45" />
</packages>`

**Comment by iccfish** [comment]
refer看来是优先级没处理好，可以通过临时关闭会话保存来避免此问题：

``` c#
client.Setting.KeepReferBetweenRequest=false;
```

至于ContentType，建议测试是否不需要此头即可使用，因为根据HTTP协议规范，无需发送数据的情况下并不会有此头，你所举例的情况我认为是网易的客户端有BUG。

**Comment by iccfish** [comment]
Fixed via  1ffb776301f6db5810aaa8b37036d480e313aaca
