### ISSUE TITLE
或许是.net自身类库的问题，但确实跟浏览器处理方式不一样

### ISSUE THREAD

**Issue by gitlsl** [iccfish/fslib.network#4]
当服务器返回 
`Set-Cookie: l_c_kaolaLYABFrz=2fbd2f3dede92e45`
就一个name 跟key  不带其他path  domain之类的时候
如果请求的网址是   http://www.a.com/1/2/3?x=s
类库就把这个  cookie的 path 当做 “/1/2/3” 来处理了   而浏览器是当 "/"来处理

**Comment by iccfish** [comment]
根据规范，如果Cookies设置的时候没有指定path，则path为当前目录，所以framework这么处理是没问题的。
这也是浏览器同样的处理模式。
