### ISSUE TITLE
此库导致无法利用net自带的发送邮件

### ISSUE THREAD

**Issue by gitlsl** [iccfish/fslib.network#5]
[https://github.com/iccfish/fslib.network/blame/master/src/FSLib.Network/Http/HttpClient.cs#L35](url)

ServicePointManager.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) =>
			{
				var e = new CertificateValidationEventArgs((HttpWebRequest)sender, sslPolicyErrors, chain, certificate);
}

这里的设置是全局的   我发邮件的时候系统也会调这个       此时sender 是 smtpclient   强制转化就抛异常了 ，  建议 用 as 判断null

**Comment by gitlsl** [comment]
然后 我在自己程序里   ServicePointManager.ServerCertificateValidationCallback  = null
又出现了大量的  基础连接已经关闭: 连接被意外关闭   网上很多说是 post参数不对  但我全都是get啊
在 app.config 里添加了网上所说的
`<system.net>
<settings>
<httpWebRequest useUnsafeHeaderParsing="true"/>
</settings>
</system.net>`
也不行。。

**Comment by iccfish** [comment]
Fixed
