### ISSUE TITLE
 client.Get<sometype>( ） 当 json 序列化抛异常的话    这个函数也接着抛了。。

### ISSUE THREAD

**Issue by gitlsl** [iccfish/fslib.network#7]
好像在博客里说到设计是 考虑  不抛异常 用 ctx.IsValid() 来判断

**Comment by iccfish** [comment]
序列化异常……这个错误是没考虑的。是指客户端发送的数据有问题？

**Comment by gitlsl** [comment]
@iccfish  是返回的数据序列号异常了 ， 然后 直接抛异常出来了，  json.net 用的是最新版

我是把fiddler抓下来的json字符串 粘贴到vs里的json类， 结果有个数字默认生成   是 int 类型转的时候就异常了，  我手工改long 就ok， 但我印象中 博客里说到设计是 考虑 不抛异常 用 ctx.IsValid() 来判断

**Comment by iccfish** [comment]
序列化异常应该是会捕捉的丫……可否提供一个测试的样本？

**Comment by gitlsl** [comment]
@iccfish    我又测试了多次 ， 应该是  ozcode 自动断在异常  实际还是有往下走的。。
不好意思 了。
